In [1]:
pip install ctgan

Collecting ctgan
  Downloading ctgan-0.7.5-py2.py3-none-any.whl (27 kB)
Requirement already satisfied: tqdm<5,>=4.15 in /usr/local/lib/python3.10/dist-packages (from ctgan) (4.66.1)
Collecting rdt<2.0,>=1.6.1 (from ctgan)
  Downloading rdt-1.7.0-py2.py3-none-any.whl (70 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.5/70.5 kB 6.7 MB/s eta 0:00:00
Requirement already satisfied: numpy<2,>=1.23.3 in /usr/local/lib/python3.10/dist-packages (from ctgan) (1.23.5)
Requirement already satisfied: scikit-learn<2,>=1.1.3 in /usr/local/lib/python3.10/dist-packages (from ctgan) (1.2.2)
Requirement already satisfied: pandas>=1.3.4 in /usr/local/lib/python3.10/dist-packages (from ctgan) (1.5.3)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from ctgan) (2.1.0+cu118)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.4->ctgan) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.4->ctgan) (2023.3.post1)
Requirement already satisfied: psutil<6,>=5.7 in /usr/local/lib/python3.10/dist-packages (from rdt<2.0,>=1.6.1->ctgan) (5.9.5)
Collecting Faker>=10 (from rdt<2.0,>=1.6.1->ctgan)
  Downloading Faker-19.11.0-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 27.7 MB/s eta 0:00:00
Requirement already satisfied: scipy<2,>=1.9.2 in /usr/local/lib/python3.10/dist-packages (from rdt<2.0,>=1.6.1->ctgan) (1.11.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2,>=1.1.3->ctgan) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2,>=1.1.3->ctgan) (3.2.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (3.12.4)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (4.5.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (3.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (2023.6.0)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (2.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=1.3.4->ctgan) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->ctgan) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.11.0->ctgan) (1.3.0)
Installing collected packages: Faker, rdt, ctgan
Successfully installed Faker-19.11.0 ctgan-0.7.5 rdt-1.7.0

In [3]:
import pandas as pd
from ctgan import CTGAN

In [12]:
df_real_data  = pd.read_csv("/content/Housing.csv")
df_real_data.shape

(545, 13)

In [9]:
# Names of the columns
column_names = list(df_real_data.columns.values)
column_names

['price',
 'area',
 'bedrooms',
 'bathrooms',
 'stories',
 'mainroad',
 'guestroom',
 'basement',
 'hotwaterheating',
 'airconditioning',
 'parking',
 'prefarea',
 'furnishingstatus']

In [13]:
ctgan = CTGAN(epochs=10)
ctgan.fit(df_real_data, column_names)

# Create synthetic data
synthetic_data = ctgan.sample(500)

In [14]:
synthetic_data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,3710000,5136,4,1,1,yes,no,no,no,no,1,yes,unfurnished
1,6293000,4260,3,3,2,no,no,yes,no,yes,3,yes,furnished
2,5250000,5720,5,1,1,yes,no,yes,no,no,2,yes,semi-furnished
3,2604000,5020,1,4,1,yes,yes,yes,yes,no,0,yes,furnished
4,5285000,4770,4,2,3,yes,yes,no,no,no,3,yes,unfurnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,4480000,4990,2,2,1,yes,yes,no,no,yes,2,no,semi-furnished
496,3990000,4500,3,1,1,yes,yes,no,no,no,2,no,unfurnished
497,3703000,3990,2,1,3,yes,no,no,no,no,1,yes,furnished
498,2835000,3816,3,3,1,yes,yes,yes,yes,no,2,no,semi-furnished
499,4760000,2990,3,4,2,no,no,no,no,no,2,no,furnished